# Generated by Django 3.1 on 2021-04-11 04:50

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name Cluster')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCluster',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name Cluster')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('InternalCode', models.CharField(db_index=True, max_length=50, verbose_name='Code internal')),
                ('uniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('observation', models.CharField(max_length=4000, verbose_name='Observation Cluster Movement')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('status_movement', models.CharField(choices=[('AC', 'Activate'), ('PR', 'Process'), ('CA', 'Canceled')], max_length=30, verbose_name='Status Movement')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductCluster',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('status_cluster', models.CharField(choices=[('SP', 'spent'), ('LI', 'Limited'), ('FU', 'Full')], max_length=150, verbose_name='Status Product in Cluster')),
                ('minimum_quantity', models.PositiveSmallIntegerField(verbose_name='Minimum Quantity Product')),
                ('observation', models.CharField(max_length=4000, verbose_name='Observation Cluster Stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='This Field Purchase PriceProduct', max_digits=6, verbose_name='Purchase Price Product in Cluster')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='This Field Sale PriceProduct', max_digits=6, verbose_name='Purchase Price Product in Cluster')),
                ('minimum_stock', models.BooleanField(default=True, help_text='this Field alarm, This product is out of stock ', verbose_name='Minimum Stock')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTypeMovement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Type  Movement')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('InternalCode', models.CharField(max_length=50, unique=True, verbose_name='Code internal')),
                ('uniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('observation', models.CharField(max_length=4000, verbose_name='Observation Cluster Movement')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('status_movement', models.CharField(choices=[('AC', 'Activate'), ('PR', 'Process'), ('CA', 'Canceled')], max_length=30, verbose_name='Status Movement')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Type  Movement')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('status_cluster', models.CharField(choices=[('SP', 'spent'), ('LI', 'Limited'), ('FU', 'Full')], max_length=150, verbose_name='Status Product in Cluster')),
                ('minimum_quantity', models.PositiveSmallIntegerField(verbose_name='Minimum Quantity Product')),
                ('observation', models.CharField(max_length=4000, verbose_name='Observation Cluster Stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='This Field Purchase PriceProduct', max_digits=6, verbose_name='Purchase Price Product in Cluster')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='This Field Sale PriceProduct', max_digits=6, verbose_name='Purchase Price Product in Cluster')),
                ('minimum_stock', models.BooleanField(default=True, help_text='this Field alarm, This product is out of stock ', verbose_name='Minimum Stock')),
                ('Cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorys.cluster')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
    ]
