# Generated by Django 3.1 on 2021-04-11 04:50

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('UniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('CodeInternal', models.CharField(max_length=10, unique=True, verbose_name='Code Unique Internal')),
                ('billing_cut', models.CharField(max_length=15, verbose_name='Date of the month where payment Bill')),
                ('billing_status', models.CharField(choices=[('CA', 'Cancel'), ('AC', 'Accredited'), ('IN', 'Invalidate')], max_length=50)),
                ('total_charged', models.DecimalField(decimal_places=2, help_text='This Field Total ChargedProducts', max_digits=6, verbose_name='Total Charged')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Product')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBill',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('UniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('CodeInternal', models.CharField(db_index=True, max_length=10, verbose_name='Code Unique Internal')),
                ('billing_cut', models.CharField(max_length=15, verbose_name='Date of the month where payment Bill')),
                ('billing_status', models.CharField(choices=[('CA', 'Cancel'), ('AC', 'Accredited'), ('IN', 'Invalidate')], max_length=50)),
                ('total_charged', models.DecimalField(decimal_places=2, help_text='This Field Total ChargedProducts', max_digits=6, verbose_name='Total Charged')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBillDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity Product')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Product')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.bill')),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
