# Generated by Django 3.1 on 2021-04-11 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('list_price', '0002_auto_20210410_2350'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbilldetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbilldetail',
            name='iva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.iva'),
        ),
        migrations.AddField(
            model_name='historicalbilldetail',
            name='listPrice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='list_price.listprice'),
        ),
        migrations.AddField(
            model_name='historicalbilldetail',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='typePlan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='list_price.typeplan'),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='typeSale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='list_price.typesale'),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.iva'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='listPrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_price.listprice'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='bill',
            name='typePlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_price.typeplan'),
        ),
        migrations.AddField(
            model_name='bill',
            name='typeSale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_price.typesale'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
