# Generated by Django 3.1 on 2021-04-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_price', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='listprice',
            name='typePlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list_price.typeplan'),
        ),
        migrations.AddField(
            model_name='listprice',
            name='typeSale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list_price.typesale'),
        ),
    ]
