# Generated by Django 3.1 on 2021-04-11 04:50

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('account', '0002_historicalaccount_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('UniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('CodeInternal', models.CharField(db_index=True, max_length=10, verbose_name='Code Unique Internal')),
                ('quota_ammount', models.DecimalField(decimal_places=2, help_text='Pay', max_digits=6, verbose_name='Pay')),
                ('quota', models.PositiveIntegerField(verbose_name='Quota Payment')),
                ('status_payment_internal', models.CharField(choices=[('PA', 'Pay'), ('NP', 'Not Pay'), ('IN', 'Invalidate'), ('OV', 'Overdue')], max_length=50, verbose_name='Status Payment')),
                ('date_payment_initial', models.DateField(verbose_name='Date Payment Initial')),
                ('date_payment_final', models.DateField(verbose_name='Date Payment Final')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTypePayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Create Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified Date')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Type Payment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Base Model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Type Payment')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('UniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('CodeInternal', models.CharField(max_length=10, unique=True, verbose_name='Code Unique Internal')),
                ('quota_ammount', models.DecimalField(decimal_places=2, help_text='Pay', max_digits=6, verbose_name='Pay')),
                ('quota', models.PositiveIntegerField(verbose_name='Quota Payment')),
                ('status_payment_internal', models.CharField(choices=[('PA', 'Pay'), ('NP', 'Not Pay'), ('IN', 'Invalidate'), ('OV', 'Overdue')], max_length=50, verbose_name='Status Payment')),
                ('date_payment_initial', models.DateField(verbose_name='Date Payment Initial')),
                ('date_payment_final', models.DateField(verbose_name='Date Payment Final')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
    ]
